//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class books
    {
        public books()
        {
            this.authors = new HashSet<authors>();
            this.genre = new HashSet<genre>();
            this.users1 = new HashSet<users>();
            this.comments = new HashSet<comments>();
        }
    
        public int id { get; set; }
        public string title { get; set; }
        public string isbn { get; set; }
        public string edition { get; set; }
        public string description { get; set; }
        public int added_by { get; set; }
        public Nullable<bool> active { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<double> rating { get; set; }
        public Nullable<int> ratingscore { get; set; }
        public Nullable<int> ratingpeople { get; set; }
        public string elastic_id { get; set; }
        public string path { get; set; }
    
        public virtual users users { get; set; }
        public virtual ICollection<authors> authors { get; set; }
        public virtual ICollection<genre> genre { get; set; }
        public virtual ICollection<users> users1 { get; set; }
        public virtual ICollection<comments> comments { get; set; }
    }
}
