//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class comments
    {
        public int id { get; set; }
        public Nullable<bool> active { get; set; }
        public string text { get; set; }
        public int idUser { get; set; }
        public int idBook { get; set; }
    
        public virtual books books { get; set; }
        public virtual users users { get; set; }
    }
}
