//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class digital_libraryEntities : DbContext
    {
        public digital_libraryEntities()
            : base("name=digital_libraryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<authors> authors { get; set; }
        public DbSet<books> books { get; set; }
        public DbSet<genre> genre { get; set; }
        public DbSet<user_types> user_types { get; set; }
        public DbSet<users> users { get; set; }
        public DbSet<comments> comments { get; set; }
    }
}
